import { defineCollection, z } from 'astro:content';
import { glob } from 'astro/loaders';

// Docs are generated by scripts/sync-docs.mjs from the canonical nervepack repo.
const docs = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/docs' }),
  schema: z.object({
    title: z.string(),
    order: z.number().default(99),
    sourcePath: z.string().optional(),
    sourceUrl: z.string().optional(),
  }),
});

export const collections = { docs };
